// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://ibrx7gq2prbexgkar3wi2wyrti.appsync-api.ap-northeast-1.amazonaws.com/graphql',
          region: 'ap-northeast-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-5yuw3gts4fgmlkyv6visrq3bpe'
        }
    }
};

export default config;
